name: Show Me the secrets
on: [push]

jobs:
  debug:
    environment: test
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code1
      uses: actions/checkout@v2

    - name: Set up secret file3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.TEAMWORK_QAA_PASSWORD }}

      run: |
        echo ${{secrets.REPO_SEC}} | sed 's/./& /g'
